<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class relationship extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('relationships')->delete();
        DB::table('relationships')->insert([
            ['user_first' => '1', 'user_second' => '2','type_id'=>1],
            ['user_first' => '1', 'user_second' => '3','type_id'=>1],
            ['user_first' => '1', 'user_second' => '4','type_id'=>1],
            ['user_first' => '1', 'user_second' => '5','type_id'=>1],
            ['user_first' => '1', 'user_second' => '6','type_id'=>1],
            ['user_first' => '1', 'user_second' => '7','type_id'=>1],
            ['user_first' => '1', 'user_second' => '8','type_id'=>1],
            ['user_first' => '1', 'user_second' => '9','type_id'=>1],
            ['user_first' => '1', 'user_second' => '10','type_id'=>1],
            ['user_first' => '1', 'user_second' => '11','type_id'=>1],
            ['user_first' => '1', 'user_second' => '12','type_id'=>1],
            ['user_first' => '1', 'user_second' => '13','type_id'=>1],
            ['user_first' => '1', 'user_second' => '14','type_id'=>1],
            ['user_first' => '1', 'user_second' => '15','type_id'=>1],
            ['user_first' => '1', 'user_second' => '16','type_id'=>1],
            ['user_first' => '1', 'user_second' => '17','type_id'=>1],
            ['user_first' => '1', 'user_second' => '18','type_id'=>1],
            ['user_first' => '1', 'user_second' => '19','type_id'=>1],
            ['user_first' => '1', 'user_second' => '20','type_id'=>1],
            ['user_first' => '2', 'user_second' => '3','type_id'=>1],
            ['user_first' => '2', 'user_second' => '4','type_id'=>1],
            ['user_first' => '2', 'user_second' => '5','type_id'=>1],
            ['user_first' => '2', 'user_second' => '6','type_id'=>1],
            ['user_first' => '2', 'user_second' => '7','type_id'=>1],
            ['user_first' => '2', 'user_second' => '8','type_id'=>1],
            ['user_first' => '2', 'user_second' => '9','type_id'=>1],
            ['user_first' => '2', 'user_second' => '10','type_id'=>1],
            ['user_first' => '2', 'user_second' => '11','type_id'=>1],
            ['user_first' => '2', 'user_second' => '12','type_id'=>1],
            ['user_first' => '2', 'user_second' => '13','type_id'=>1],
            ['user_first' => '2', 'user_second' => '14','type_id'=>1],
            ['user_first' => '2', 'user_second' => '15','type_id'=>1],
            ['user_first' => '2', 'user_second' => '16','type_id'=>1],
            ['user_first' => '2', 'user_second' => '17','type_id'=>1],
            ['user_first' => '2', 'user_second' => '18','type_id'=>1],
            ['user_first' => '2', 'user_second' => '19','type_id'=>1],
            ['user_first' => '2', 'user_second' => '20','type_id'=>1],
            ['user_first' => '3', 'user_second' => '4','type_id'=>1],
            ['user_first' => '3', 'user_second' => '5','type_id'=>1],
            ['user_first' => '3', 'user_second' => '6','type_id'=>1],
            ['user_first' => '3', 'user_second' => '7','type_id'=>1],
            ['user_first' => '3', 'user_second' => '8','type_id'=>1],
            ['user_first' => '3', 'user_second' => '9','type_id'=>1],
            ['user_first' => '3', 'user_second' => '10','type_id'=>1],
            ['user_first' => '3', 'user_second' => '11','type_id'=>1],
            ['user_first' => '3', 'user_second' => '12','type_id'=>1],
            ['user_first' => '3', 'user_second' => '13','type_id'=>1],
            ['user_first' => '3', 'user_second' => '14','type_id'=>1],
            ['user_first' => '3', 'user_second' => '15','type_id'=>1],
            ['user_first' => '3', 'user_second' => '16','type_id'=>1],
            ['user_first' => '3', 'user_second' => '17','type_id'=>1],
            ['user_first' => '3', 'user_second' => '18','type_id'=>1],
            ['user_first' => '3', 'user_second' => '19','type_id'=>1],
            ['user_first' => '3', 'user_second' => '20','type_id'=>1],
            ['user_first' => '4', 'user_second' => '5','type_id'=>1],
            ['user_first' => '4', 'user_second' => '6','type_id'=>1],
            ['user_first' => '4', 'user_second' => '7','type_id'=>1],
            ['user_first' => '4', 'user_second' => '8','type_id'=>1],
            ['user_first' => '4', 'user_second' => '9','type_id'=>1],
            ['user_first' => '4', 'user_second' => '10','type_id'=>1],
            ['user_first' => '4', 'user_second' => '11','type_id'=>1],
            ['user_first' => '4', 'user_second' => '12','type_id'=>1],
            ['user_first' => '4', 'user_second' => '13','type_id'=>1],
            ['user_first' => '4', 'user_second' => '14','type_id'=>1],
            ['user_first' => '4', 'user_second' => '15','type_id'=>1],
            ['user_first' => '4', 'user_second' => '16','type_id'=>1],
            ['user_first' => '4', 'user_second' => '17','type_id'=>1],
            ['user_first' => '4', 'user_second' => '18','type_id'=>1],
            ['user_first' => '4', 'user_second' => '19','type_id'=>1],
            ['user_first' => '4', 'user_second' => '20','type_id'=>1],
            ['user_first' => '5', 'user_second' => '6','type_id'=>1],
            ['user_first' => '5', 'user_second' => '7','type_id'=>1],
            ['user_first' => '5', 'user_second' => '8','type_id'=>1],
            ['user_first' => '5', 'user_second' => '9','type_id'=>1],
            ['user_first' => '5', 'user_second' => '10','type_id'=>1],
            ['user_first' => '5', 'user_second' => '11','type_id'=>1],
            ['user_first' => '5', 'user_second' => '12','type_id'=>1],
            ['user_first' => '5', 'user_second' => '13','type_id'=>1],
            ['user_first' => '5', 'user_second' => '14','type_id'=>1],
            ['user_first' => '5', 'user_second' => '15','type_id'=>1],
            ['user_first' => '5', 'user_second' => '16','type_id'=>1],
            ['user_first' => '5', 'user_second' => '17','type_id'=>1],
            ['user_first' => '5', 'user_second' => '18','type_id'=>1],
            ['user_first' => '5', 'user_second' => '19','type_id'=>1],
            ['user_first' => '5', 'user_second' => '20','type_id'=>1],
            ['user_first' => '6', 'user_second' => '7','type_id'=>1],
            ['user_first' => '6', 'user_second' => '8','type_id'=>1],
            ['user_first' => '6', 'user_second' => '9','type_id'=>1],
            ['user_first' => '6', 'user_second' => '10','type_id'=>1],
            ['user_first' => '6', 'user_second' => '11','type_id'=>1],
            ['user_first' => '6', 'user_second' => '12','type_id'=>1],
            ['user_first' => '6', 'user_second' => '13','type_id'=>1],
            ['user_first' => '6', 'user_second' => '14','type_id'=>1],
            ['user_first' => '6', 'user_second' => '15','type_id'=>1],
            ['user_first' => '6', 'user_second' => '16','type_id'=>1],
            ['user_first' => '6', 'user_second' => '17','type_id'=>1],
            ['user_first' => '6', 'user_second' => '18','type_id'=>1],
            ['user_first' => '6', 'user_second' => '19','type_id'=>1],
            ['user_first' => '6', 'user_second' => '20','type_id'=>1],
            ['user_first' => '7', 'user_second' => '8','type_id'=>1],
            ['user_first' => '7', 'user_second' => '9','type_id'=>1],
            ['user_first' => '7', 'user_second' => '10','type_id'=>1],
            ['user_first' => '7', 'user_second' => '11','type_id'=>1],
            ['user_first' => '7', 'user_second' => '12','type_id'=>1],
            ['user_first' => '7', 'user_second' => '13','type_id'=>1],
            ['user_first' => '7', 'user_second' => '14','type_id'=>1],
            ['user_first' => '7', 'user_second' => '15','type_id'=>1],
            ['user_first' => '7', 'user_second' => '16','type_id'=>1],
            ['user_first' => '7', 'user_second' => '17','type_id'=>1],
            ['user_first' => '7', 'user_second' => '18','type_id'=>1],
            ['user_first' => '7', 'user_second' => '19','type_id'=>1],
            ['user_first' => '7', 'user_second' => '20','type_id'=>1],
            ['user_first' => '8', 'user_second' => '9','type_id'=>1],
            ['user_first' => '8', 'user_second' => '10','type_id'=>1],
            ['user_first' => '8', 'user_second' => '11','type_id'=>1],
            ['user_first' => '8', 'user_second' => '12','type_id'=>1],
            ['user_first' => '8', 'user_second' => '13','type_id'=>1],
            ['user_first' => '8', 'user_second' => '14','type_id'=>1],
            ['user_first' => '8', 'user_second' => '15','type_id'=>1],
            ['user_first' => '8', 'user_second' => '16','type_id'=>1],
            ['user_first' => '8', 'user_second' => '17','type_id'=>1],
            ['user_first' => '8', 'user_second' => '18','type_id'=>1],
            ['user_first' => '8', 'user_second' => '19','type_id'=>1],
            ['user_first' => '8', 'user_second' => '20','type_id'=>1],
        ]);
    }
}
